### PR TITLE
Support "$ref", functionality & code cleanups

### PR DESCRIPTION
**Pull request by agoose77**
* Added support for internal and external "$ref" fields. References can be resolved for file: and http(s): schemes.
* Rename `Json` to `JSON` in identifiers
* Support array item removal (from end of list)
* Support varied array item schemas
* Render array as list of item indices with single stack element (compact and easier to use)
* Add validation checker as schema updated
* Update readme

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Holy moly! This is amazing work.

Give me a day or two to review, but damn dude, good job!

**Comment by LegoStormtroopr** [comment]
This all looks good. Lemme know when you are ready for me to pull it  in.

**Comment by agoose77** [comment]
It could be merged, but I would like to (at some point), add support for those validators mentioned in the readme

**Comment by agoose77** [comment]
@LegoStormtroopr I think this is good for now.

I've added a much better validation error message, and fixed some bugs. 
In addition, we now support the string "format" validation with string widget itself

**Comment by agoose77** [comment]
Added support for a color picker & date-time input

**Pull request merged**
